config/routes.rb
UserContacts::Application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations", :sessions => "sessions"} do
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end
  devise_scope :user do

  end

  resources :users, only: [:index] do
    resources :contacts
    member do
      get 'test_method'
    end
  end
  resources :pictures

  

   root :to => "contacts#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
    user ||= User.new
    if user.has_role? :admin
      can :manage, :all
    
    elsif user.has_role? :site_user
      can :read, Contact
    end
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  resourcify
  attr_accessible :first_name, :last_name, :gender, :age, :phone_number, :email, :area

  has_many :informations, :dependent => :destroy
  has_many :users, :through => :informations

  validates :first_name, :last_name, :gender, :age, :phone_number, :email, :area, presence: true
  validates :first_name, :last_name, :format => { :with => /^[A-z]+$/ }
  validates :phone_number,:age, numericality: {only_integer: true}
  validates :phone_number, length: { is: 10 }
  validates :email, uniqueness: true, :on => :create
  validates :email, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }
end

app/models/information.rb
class Information < ActiveRecord::Base
  # attr_accessible :title, :body
#  att_accessible :contact_id
  belongs_to :contact
  belongs_to :user
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  attr_accessible :image, :name, :remote_image_url
  mount_uploader :image, ImageUploader
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :informations, :dependent => :destroy
  has_many :contacts, :through => :informations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
  rescue_from CanCan::AccessDenied do |exception|
  	redirect_to main_app.root_url, :alert => exception.message
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contacts
    @contacts = Contact.all
  end

  def create
    @contact = Contact.new(params[:contact])
    @user = User.find_by_id(params[:user_id])

    @contact.users << @user
    if @contact.save
      flash[:success] = 'Contact created successfully'
      redirect_to user_contacts_path(@user.id) 
    else
      flash[:error] = 'Contact could not be saved'
      render action: 'new'
    end
  end

  def new
    @user = User.find_by_id(params[:user_id])
    @contact = Contact.new
  end

  def edit
    @user = current_user
    @contact = Contact.find_by_id(params[:id])
  end

  def show
    @user = current_user
    @contact = Contact.find_by_id(params[:id])
  end

  def update
    @user = current_user
    @contact = Contact.find_by_id(params[:id])
    if @contact.last_name.present? 
      debugger
     @contact.last_name = @contact.last_name.slice(0,1).capitalize + @contact.last_name.slice(1..-1)
    end
    if @contact.update_attributes(params[:contact])
      flash[:success] = 'Contact updated successfully'
      redirect_to user_contact_path(current_user.id, @contact.id)     
    else
      render  action: :edit
    end
  end

  def destroy
    @contact = Contact.find_by_id(params[:id])
    @contact.destroy
    flash[:notice] = 'Contact successfully deleted'
    redirect_to action: 'index' 
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def new
    @picture = Picture.new
  end
  def index
    @pictures = Picture.all
  end
  def edit 
    @picture = Picture.find_by_id(params[:id])
  end
  def create
 # 	debugger
  	@picture = Picture.new(params[:picture])
  	@picture.save
  	redirect_to pictures_path
  end  
  def destroy
    @picture = Picture.find_by_id(params[:id])
    @picture.destroy
    redirect_to pictures_path
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def create
    #build_resource(sign_up_params)
    @user = User.new(params[:user])
    if @user.save
      if @user.active_for_authentication?
        set_flash_message :notice, :signed_up if is_navigational_format?
        @user.add_role "site_user"
        sign_in(@user)
        respond_with @user, :location => after_sign_up_path_for(@user)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_navigational_format?
        expire_session_data_after_sign_in!
        respond_with resource, :location => after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      respond_with resource
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  def create
   super 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/edit.html.erb
  <%= render :partial => "shared/error_messages", :locals => { :target => @contact } %>
<%= form_for([@user, @contact], url: user_contact_path(@user.id, @contact.id), method: :put) do |f| %>

  <%= f.label :first_name %>
  <%= f.text_field :first_name %></br>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %></br>
  <%= f.label :gender %>
  <%= f.select(:gender, [["M", "M"], ["F", "F"]]) %></br>
  <%= f.label :age %>
  <%= f.text_field :age %></br>
  <%= f.label :phone_number %>
  <%= f.text_field :phone_number %></br>
  <%= f.label :email %>
  <%= f.text_field :email %></br>
  <%= f.label :area %>
  <%= f.text_field :area %></br>
  <%= f.submit %>
<% end %>

app/views/contacts/index.html.erb
<h1>Contacts</h1>
<p><%= flash[:notice] %></p>
<p><%= flash[:success] %></p>

<table class="table table-bordered">
  <% unless @contacts.blank? %>
<tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Gender</th>
    <th>Age</th>
    <th>Phone Number</th>
    <th>Email</th>
    <th>Area</th>
    <th></th>
    <th></th>
</tr>
  <% @contacts.each do |contact| %>
  <tr>
      <td><%= contact.first_name %></td>
      <td><%= contact.last_name %></td>
      <td><%= contact.gender %></td>
      <td><%= contact.age.to_i %></td>
      <td><%= contact.phone_number.to_i %></td>
      <td><%= contact.email %></td>
      <td><%= contact.area %></td>
      <td><%= link_to "Edit", edit_user_contact_path(current_user.id, contact.id) %></td>
      <td><%= link_to "Delete", user_contact_path(current_user.id, contact.id), confirm: "Delete Contact ?", method: :delete %></td>
  </tr>
  <% end -%>
  <%end%>
</table>
<%= link_to "Add New Contact", new_user_contact_path(current_user.id), class: "btn pull-right" %>

app/views/contacts/new.html.erb
<h1>Add Contact</h1>
<%= form_for [@user, @contact],url: user_contacts_path(@user.id), method: :post do |f| %>
  <%= render "shared/error_messages", :target => @contact %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  <br/>  
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  <br/>
  <%= f.label :age %>
  <%= f.text_field :age %>
  <br/>
  <%= f.label :gender %>
  <%= f.select(:gender, options_for_select([['M', 'M'], ['F','F']]))%>
  
  <br/>  
  <%= f.label :phone_number %>
  <%= f.text_field :phone_number %>
  <br/>  
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br/>  
  <%= f.label :area %>
  <%= f.text_field :area %>
  <br/>
  <br/>
  <%= f.submit %>
  <%= link_to "Back", user_contacts_path(@user, @contact), class: "btn"%>
<%end%>

app/views/contacts/show.html.erb
<p id="notice"></p>
<br/><br/>
<table class="table table-bordered" width="300">
  <tr>
    <td>First Name : </td>
    <td><%= @contact.first_name%></td>
  </tr>
    <tr>
    <td>Last Name : </td>
    <td><%= @contact.last_name%></td>
  </tr>
    <tr>
    <td>Age : </td>
    <td><%= @contact.age%></td>
  </tr>
    <tr>
    <td>Gender : </td>
    <td><%= @contact.gender%></td>
  </tr>
    <tr>
    <td>Phone Number : </td>
    <td><%= @contact.phone_number.to_i %></td>
  </tr>
    <tr>
    <td>Email : </td>
    <td><%= @contact.email%></td>
  </tr>
    <tr>
    <td>Area : </td>
    <td><%= @contact.area%></td>
  </tr>
</table>
<%= link_to "Back", edit_user_contact_path(@user.id, @contact.id), class: "btn btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UserContacts</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="home" align="left" class="btn btn-link">
  <% if user_signed_in? %>
    <%= link_to "HOME", user_contacts_path(current_user.id) %>
  <% end %>
</div>

<div id="user_nav" align="right">
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>. Not you?
<%= link_to "Sign out", 
destroy_user_session_path, :method => :delete%>
  <% else %>

  <% end %>
</div>

<%= yield %>

</body>
</html>

app/views/pictures/edit.html.erb
<h1>Editing picture</h1>
<%= form_for @picture,:html => {:multipart => true} do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.file_field :image %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/pictures/index.html.erb
<h1>All pictures</h1>
<% @pictures.each do |picture| %>
  <div class="painting">
    <%= image_tag picture.image_url.to_s %>
    <div class="name"><%= picture.name%></div>
    <div class="actions">
      <%= link_to "Edit", edit_picture_path(picture)%>
      <%= link_to "Remove", picture, :confirm => "Are you sure?", :method => :delete %>
    </div>
  </div>
<% end %>

app/views/pictures/new.html.erb
<%= form_for @picture,:html => {:multipart => true} do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.file_field :image %>
  </p>
  <p>
    <%= f.label :remote_image_url, "or image Url" %>
    <%= f.text_field :remote_image_url %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/shared/_error_messages.html.erb
<% if target && target.errors.any? %>
<div id="ErrorExplanation">
  <h2><%= pluralize(target.errors.count, "error")%> prohibited the record from being saved :</h2>
  <ul>
  	<% target.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
  	<% end %>
  </ul>
</div>
<% end %>

app/views/users/index.html.erb
<h1>All Users</h1>
<table class="table table-bordered">
  <tr>
    <th>Email</th>
    <th>Total Sign-in-count</th>
  </tr>
<% @users.each do |user| %>
  <tr>
  	<td><%= user.email%></td>
	<td><%= user.sign_in_count %></td>
  </tr>
<% end %>
</table>

app/views/users/test_method.html.erb
<h1>Test Method</h1>